# Generated by Django 4.1.7 on 2023-12-11 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id_alojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alojamiento', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo_vacacional',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('id_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservalojamiento', to='alojamientoslist_app.alojamiento', verbose_name='alojamientos')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservacionlist', to='alojamientoslist_app.periodo_vacacional', verbose_name='periodos')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personareserva', to=settings.AUTH_USER_MODEL, verbose_name='personas')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipio', to='alojamientoslist_app.provincia', verbose_name='provincias')),
            ],
        ),
    ]
