# Generated by Django 4.1.7 on 2023-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alojamiento', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
