# Generated by Django 4.1.7 on 2023-12-08 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id_alojamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alojamiento', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo_vacacional',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=32)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('correo', models.EmailField(max_length=254, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alojamientoslist_app.cargo', verbose_name='Los cargos relacionados')),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alojamientoslist_app.municipio', verbose_name='Los municipios relacionados')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cancelada', models.BooleanField(default=False)),
                ('id_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alojamientoslist_app.alojamiento')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alojamientoslist_app.periodo_vacacional')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamientoslist_app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alojamientoslist_app.provincia', verbose_name='Las provincias relacionadas'),
        ),
    ]
