# Generated by Django 4.1.7 on 2023-12-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientoslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipio', to='alojamientoslist_app.provincia', verbose_name='provincias'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personacargo', to='alojamientoslist_app.cargo', verbose_name='cargos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personamunicipio', to='alojamientoslist_app.municipio', verbose_name='municipios'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='id_alojamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservalojamiento', to='alojamientoslist_app.alojamiento', verbose_name='alojamientos'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='id_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservacionlist', to='alojamientoslist_app.periodo_vacacional', verbose_name='periodos'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personareserva', to='alojamientoslist_app.persona', verbose_name='personas'),
        ),
    ]
