# Generated by Django 4.1.7 on 2023-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientoslist_app', '0002_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo_vacacional',
            fields=[
                ('id_periodo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
