# Generated by Django 4.1.7 on 2023-12-08 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamientoslist_app', '0002_alter_municipio_id_provincia_alter_persona_id_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
            preserve_default=False,
        ),
    ]
